apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectstore-manager
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: os4ml
      name: objectstore-manager
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        name: objectstore-manager
    spec:
      containers:
        - name: objectstore-manager
          image: "gitlab-registry.wogra.com/developer/wogra/os4ml/objectstore-manager"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          env:
            - name: OBJECTSTORE_STORAGE_BACKEND
              valueFrom:
                configMapKeyRef:
                  key: storageBackend
                  name: objectstore-config
            - name: OBJECTSTORECONFIG_URL
              valueFrom:
                configMapKeyRef:
                  name: objectstore-config
                  key: url
            - name: OBJECTSTORECONFIG_SECURE
              valueFrom:
                configMapKeyRef:
                  name: objectstore-config
                  key: objectstoreSecure
            - name: OS4ML_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: objectstore-config
                  key: bucketName
            - name: OBJECTSTORECONFIG_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: accesskey
            - name: OBJECTSTORECONFIG_SECRETACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: secretkey
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/gcs-creds/.credentials.json
          volumeMounts:
            - mountPath: /var/gcs-creds
              name: gcs-creds
              readOnly: true
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 200Mi
          readinessProbe:
            httpGet:
              port: http
              path: /docs
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: gcs-creds
          secret:
            secretName: google-credentials
            optional: true
      serviceAccountName: service-account
      imagePullSecrets:
          - name: registry-credentials
