apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: os4ml-
namespace: os4ml
resources:
  - objectstore-config.yaml
  - os4ml-minio-secret.yaml
  - service.yaml
  - deployment.yaml
