apiVersion: v1
kind: ConfigMap
metadata:
  name: objectstore-config
data:
  storageBackend: 'gcs'
  bucketName: 'os4ml'
  url: 'minio.minio-tenant.svc.cluster.local'
  templateBucket: 'templates'
  objectstoreSecure: 'false'
