apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: os4ml
commonLabels:
  app.kubernetes.io/name: os4ml
resources:
  - deployment.yaml
  - model-manager-config.yaml
  - service.yaml
