apiVersion: v1
kind: Service
metadata:
  name: model-manager
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
      targetPort: http
      name: api
  selector:
    app: os4ml
    name: model-manager