apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: os4ml
      app.kubernetes.io/component: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: os4ml
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "wogra/os4ml-frontend"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
          startupProbe:
            httpGet:
              port: http
              path: /
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: http
              path: /
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 4
          livenessProbe:
            httpGet:
              port: http
              path: /
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 4
          securityContext:
            allowPrivilegeEscalation: false
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
      serviceAccountName: service-account
      imagePullSecrets:
        - name: registry-credentials
