apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: os4ml
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: os4ml
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: "gitlab-registry.wogra.com/developer/wogra/os4ml/frontend"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
          readinessProbe:
            httpGet:
              port: http
              path: /
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
      serviceAccountName: service-account
      imagePullSecrets:
        - name: registry-credentials
