apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: os4ml
    tier: frontend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP
