include:
  - local: 'gitlab/.gitlab-ci.terraform.yml'
  - local: 'gitlab/services/.gitlab-ci.frontend.yml'
  - local: 'gitlab/services/.gitlab-ci.job-manager.yml'
  - local: 'gitlab/services/.gitlab-ci.objectstore-manager.yml'

stages:
  - prepare
  - test
  - build
  - deploy
  - clean

variables:
  SWAGGER_CLI_VERSION: 4.0.4

.validate-oas:
  stage: prepare
  needs: []
  image: node:14
  script:
    - npm install -g swagger-cli@$SWAGGER_CLI_VERSION
    - swagger-cli validate $OAS_FILE
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH'
      changes:
        - $OAS_FILE
      when: on_success
