include:
  - local: 'gitlab/.gitlab-ci.terraform.yml'
  - local: 'gitlab/.gitlab-ci.templates.yml'
  - local: 'gitlab/.gitlab-ci.build-templates.yml'
  - local: 'gitlab/.gitlab-ci.enas-trial.yml'
  - local: 'gitlab/services/.gitlab-ci.frontend.yml'
  - local: 'gitlab/services/.gitlab-ci.job-manager.yml'
  - local: 'gitlab/services/.gitlab-ci.objectstore-manager.yml'

stages:
  - prepare
  - test
  - build
  - deploy
  - clean

variables:
  SWAGGER_CLI_VERSION: 4.0.4

.deploy:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context $DIR
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --destination $CI_REGISTRY_IMAGE/$IMG_NAME:$LABEL
  when: manual

.frontend-deploy-prod:
  extends:
    .deploy
  needs: [
    build-frontend,
    build-frontend-image
  ]
  dependencies:
    - build-frontend
  variables:
    DIR: 'services/frontend'
    IMG_NAME: 'frontend'
    LABEL: 'latest'
  rules:
    - if: '$CI_COMMIT_TAG'

.frontend-deploy-staging:
  extends:
    .deploy
  needs: [
    build-frontend,
    build-frontend-image
  ]
  dependencies:
    - build-frontend
  variables:
    DIR: 'services/frontend'
    IMG_NAME: 'frontend'
    LABEL: 'stage'
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG'

.frontend-deploy-release:
  extends:
    .deploy
  needs: [
    build-frontend,
    build-frontend-image
  ]
  dependencies:
    - build-frontend
  variables:
    DIR: 'services/frontend'
    IMG_NAME: 'frontend'
    LABEL: 'rc'

.frontend-deploy-dev:
  extends:
    .deploy
  needs: [
    build-frontend,
    build-frontend-image
  ]
  dependencies:
    - build-frontend
  variables:
    DIR: 'services/frontend'
    IMG_NAME: 'frontend'
    LABEL: 'dev'

.frontend-deploy-feature:
  extends:
    .deploy
  needs: [
    build-frontend,
    build-frontend-image
  ]
  dependencies:
    - build-frontend
  variables:
    DIR: 'services/frontend'
    IMG_NAME: 'frontend'
    LABEL: 'feature'

.jobmanager-deploy-dev:
  extends:
    - .deploy
  needs:
    - job-manager-validate-backend
  variables:
    DIR: 'services/job-manager'
    IMG_NAME: 'job-manager'
    LABEL: 'dev'

.objectstore-deploy-dev:
  extends:
    - .deploy
  needs:
    - os-manager-validate-backend
  variables:
    DIR: 'services/objectstore-manager'
    IMG_NAME: 'objectstore-manager'
    LABEL: 'dev'

deploy-dev:
  extends:
    - .frontend-deploy-dev
    - .objectstore-deploy-dev
    - .jobmanager-deploy-dev
  needs:
    - build-frontend