apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    run: os4ml
  namespace: os4ml
spec:
  selector:
    app: os4ml
    tier: frontend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5001
  type: ClusterIP
