.build-test-and-lint:
  stage: test
  services:
    - name: docker:20.10.14-dind
      command: ["--registry-mirror", "http://172.16.10.15:5000", "--registry-mirror", "http://172.16.10.15:5001"]  # Specify the registry mirror to use
  image: docker:20.10.14
  script:
    - docker build
      -f $DOCKERFILE
      --target lint
      --cache-from $CI_REGISTRY_IMAGE/$IMG_NAME:lint
      --tag $CI_REGISTRY_IMAGE/$IMG_NAME:lint
      --build-arg BUILDKIT_INLINE_CACHE=1
      $BUILD_CONTEXT
    - docker push $CI_REGISTRY_IMAGE/$IMG_NAME:lint
    - docker build
      -f $DOCKERFILE
      --target test
      --cache-from $CI_REGISTRY_IMAGE/$IMG_NAME:lint
      --tag $CI_REGISTRY_IMAGE/$IMG_NAME:test
      --build-arg BUILDKIT_INLINE_CACHE=1
      $BUILD_CONTEXT
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
