.build-lint:
  stage: test
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${BUILD_CONTEXT}"
      --dockerfile "$DOCKERFILE"
      --target lint
      --destination "$CI_REGISTRY_IMAGE/$IMG_NAME:lint"
      --digest-file=$CI_PROJECT_DIR/image-digest
      --cache=true
      --cache-ttl 2190h0m0s
      --cache-repo=172.16.10.15:6000/$IMG_NAME/cache
      --cache=true
      --insecure=true
      --insecure-registry=172.16.10.15:6000
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    name: image-digest
    paths:
      - image-digest
    expire_in: never

.build-test:
  stage: test
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${BUILD_CONTEXT}"
      --dockerfile "$DOCKERFILE"
      --target test
      --destination "$CI_REGISTRY_IMAGE/$IMG_NAME:test"
      --digest-file=$CI_PROJECT_DIR/image-digest
      --cache=true
      --cache-ttl 2190h0m0s
      --cache-repo=172.16.10.15:6000/$IMG_NAME/cache
      --cache=true
      --insecure=true
      --insecure-registry=172.16.10.15:6000
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    name: image-digest
    paths:
      - image-digest
    expire_in: never
