.build-production:
  stage: build
  services:
    - docker:20.10.14-dind
  image: docker:20.10.14
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build
      -f $DOCKERFILE
      --target production
      --cache-from $CI_REGISTRY_IMAGE/$IMG_NAME:$CI_COMMIT_REF_NAME
      --tag $CI_REGISTRY_IMAGE/$IMG_NAME:$CI_COMMIT_SHA
      --tag $CI_REGISTRY_IMAGE/$IMG_NAME:$CI_COMMIT_REF_NAME
      --build-arg BUILDKIT_INLINE_CACHE=1
      $BUILD_CONTEXT
    - docker push $CI_REGISTRY_IMAGE/$IMG_NAME:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/$IMG_NAME:$CI_COMMIT_REF_NAME
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1