.build-template:
  stage: build
  when: on_success
  services:
    - docker:20.10.14-dind
  image: docker:20.10.14
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd $DIR
    - docker build
      --target production
      --cache-from $CI_REGISTRY_IMAGE/$IMG_NAME:$LABEL
      --tag $CI_REGISTRY_IMAGE/$IMG_NAME:$LABEL
      --build-arg BUILDKIT_INLINE_CACHE=1
      "$DOCKERFILE"
    - docker push --tag $CI_REGISTRY_IMAGE/$IMG_NAME:$LABEL
  variables:
    LABEL: $CI_COMMIT_REF_NAME
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "main"'
      variables:
        LABEL: "latest"
    - if: '$CI_COMMIT_BRANCH == "main"'
      variables:
        LABEL: "latest"
    - if: '$CI_COMMIT_TAG'
      variables:
        LABEL: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH'
      changes:
        - $DIR
    - if: '$CI_COMMIT_BRANCH'
      changes:
        - $DIR