.build-test-and-lint:
  stage: test
  services:    
    - name: docker:dind
      command: ["--tls=false"]
  tags:
    - aime
  script:
    - docker pull alpine
    - docker build
      -f $DOCKERFILE
      --target lint
      --cache-from $CI_REGISTRY_IMAGE/$IMG_NAME:$CI_COMMIT_REF_NAME
      --build-arg BUILDKIT_INLINE_CACHE=1
      --tag $CI_REGISTRY_IMAGE/$IMG_NAME:lint
      $BUILD_CONTEXT
    - docker push $CI_REGISTRY_IMAGE/$IMG_NAME
    - docker build
      -f $DOCKERFILE
      --target test
      --cache-from $CI_REGISTRY_IMAGE/$IMG_NAME:test
      --build-arg BUILDKIT_INLINE_CACHE=1
      --tag $CI_REGISTRY_IMAGE/$IMG_NAME:test
      $BUILD_CONTEXT
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    DOCKER_TLS_CERTDIR: ""
