distribute-oas:
  stage: prepare
  needs: []
  script:
    - cd services/oas
    - sh distribute_oas.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE

.validate-oas:
  stage: prepare
  needs: [distribute-oas]
  image: node:20
  script:
    - npm install -g swagger-cli@$SWAGGER_CLI_VERSION
    - swagger-cli validate $OAS_FILE
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE