.build-test-and-lint:
  stage: test
  services:    
    - name: docker:dind
      command: ["--tls=false"]
  tags:
    - aime
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/$IMG_NAME:$CI_COMMIT_REF_NAME:lint
    - docker build
      -f $DOCKERFILE
      --target lint
      --cache-from $CI_REGISTRY_IMAGE/$IMG_NAME:$CI_COMMIT_REF_NAME
      --tag $CI_REGISTRY_IMAGE/$IMG_NAME:lint
      $BUILD_CONTEXT
    - docker push $CI_REGISTRY_IMAGE/$IMG_NAME:lint
    - docker pull $CI_REGISTRY_IMAGE/$IMG_NAME:$CI_COMMIT_REF_NAME:test
    - docker build
      -f $DOCKERFILE
      --target test
      --cache-from $CI_REGISTRY_IMAGE/$IMG_NAME:test
      --tag $CI_REGISTRY_IMAGE/$IMG_NAME:test
      $BUILD_CONTEXT
    - docker push $CI_REGISTRY_IMAGE/$IMG_NAME:test
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
