.build-test-and-lint:
  stage: test
  services:    
    - name: docker:dind
      command: ["--tls=false"]
  tags:
    - aime
  script:
    - docker pull developer/wogra/os4ml/$IMG_NAME:lint
    - docker build
      -f $DOCKERFILE
      --target lint
      --cache-from developer/wogra/os4ml/$IMG_NAME:lint
      --build-arg BUILDKIT_INLINE_CACHE=1
      --tag developer/wogra/os4ml/$IMG_NAME:lint
      $BUILD_CONTEXT
    - docker push developer/wogra/os4ml/$IMG_NAME:lint
    - docker pull developer/wogra/os4ml/$IMG_NAME:test
    - docker build
      -f $DOCKERFILE
      --target test
      --cache-from developer/wogra/os4ml/$IMG_NAME:test
      --build-arg BUILDKIT_INLINE_CACHE=1
      --tag developer/wogra/os4ml/$IMG_NAME:test
      $BUILD_CONTEXT
    - docker push developer/wogra/os4ml/$IMG_NAME:test
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    DOCKER_TLS_CERTDIR: ""
