.build-development:
  stage: test
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --target test
      --context $DIR
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --destination $CI_REGISTRY_IMAGE/$IMG_NAME:test
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH'
      changes:
        - $DIR/**/*
      when: on_success
