.build-lint:
  stage: test
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$CI_DEPENDENCY_PROXY_SERVER\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${BUILD_CONTEXT}"
      --dockerfile "$DOCKERFILE"
      --target lint
      --destination "$CI_REGISTRY_IMAGE/$IMG_NAME:lint"
      --digest-file=$CI_PROJECT_DIR/image-digest
      --cache=true
      --cache-repo $CI_REGISTRY/$IMG_NAME-cache
      --cache-ttl 2190h0m0s
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    name: image-digest
    paths:
      - image-digest
    expire_in: never

.build-test:
  stage: test
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$CI_DEPENDENCY_PROXY_SERVER\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${BUILD_CONTEXT}"
      --dockerfile "$DOCKERFILE"
      --target test
      --destination "$CI_REGISTRY_IMAGE/$IMG_NAME:test"
      --digest-file=$CI_PROJECT_DIR/image-digest
      --cache=true
      --cache-repo $CI_REGISTRY/$IMG_NAME-cache
      --cache-ttl 2190h0m0s
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    name: image-digest
    paths:
      - image-digest
    expire_in: never

