.build-production:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --target production
      --context $DIR
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --destination $CI_REGISTRY_IMAGE/$IMG_NAME:$CI_COMMIT_SHA
      --destination $CI_REGISTRY_IMAGE/$IMG_NAME:$CI_COMMIT_REF_NAME
