.build-test-and-lint:
  stage: test
  services:    
  - name: docker:dind
    command: ["--tls=false"]
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build
      -f $DOCKERFILE
      --target lint
      --tag $CI_REGISTRY_IMAGE/$IMG_NAME:lint
      $BUILD_CONTEXT
    - docker push $CI_REGISTRY_IMAGE/$IMG_NAME:lint
    - docker build
      -f $DOCKERFILE
      --target test
      --tag $CI_REGISTRY_IMAGE/$IMG_NAME:test
      $BUILD_CONTEXT
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
