deploy-prod:
  stage: deploy
  needs:
    - build-frontend
    - build-frontend-image
    - job-manager-build
    - os-manager-build
  dependencies:
    - build-frontend
  variables:
    LABEL: 'latest'
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --target production
      --context services/objectstore-manager
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --cleanup
      --destination $CI_REGISTRY_IMAGE/objectstore-manager:$LABEL
    - rm -R /kaniko/2/opt/pysetup
    - /kaniko/executor
      --target production
      --context services/job-manager
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --cleanup
      --destination $CI_REGISTRY_IMAGE/job-manager:$LABEL
    - /kaniko/executor
      --context services/frontend
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --cleanup
      --destination $CI_REGISTRY_IMAGE/frontend:$LABEL
  when: manual
  rules:
    - if: '$CI_COMMIT_TAG'

deploy-staging:
  stage: deploy
  needs:
    - build-frontend
    - build-frontend-image
    - job-manager-build
    - os-manager-build
  dependencies:
    - build-frontend
  variables:
    LABEL: 'stage'
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --target production
      --context services/objectstore-manager
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --cleanup
      --destination $CI_REGISTRY_IMAGE/objectstore-manager:$LABEL
    - rm -R /kaniko/2/opt/pysetup
    - /kaniko/executor
      --target production
      --context services/job-manager
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --cleanup
      --destination $CI_REGISTRY_IMAGE/job-manager:$LABEL
    - /kaniko/executor
      --context services/frontend
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --cleanup
      --destination $CI_REGISTRY_IMAGE/frontend:$LABEL
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: $CI_COMMIT_REF_NAME =~ /^hotfix/
    - if: '$CI_COMMIT_TAG'

deploy-release:
  stage: deploy
  needs:
    - build-frontend
    - build-frontend-image
    - job-manager-build
    - os-manager-build
  dependencies:
    - build-frontend
  variables:
    LABEL: 'rc'
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --target production
      --context services/objectstore-manager
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --cleanup
      --destination $CI_REGISTRY_IMAGE/objectstore-manager:$LABEL
    - rm -R /kaniko/2/opt/pysetup
    - /kaniko/executor
      --target production
      --context services/job-manager
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --cleanup
      --destination $CI_REGISTRY_IMAGE/job-manager:$LABEL
    - /kaniko/executor
      --context services/frontend
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --cleanup
      --destination $CI_REGISTRY_IMAGE/frontend:$LABEL
  when: manual
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^rc/
    - if: $CI_COMMIT_REF_NAME =~ /^release/

deploy-dev:
  stage: deploy
  needs:
    - build-frontend
    - build-frontend-image
    - job-manager-build
    - os-manager-build
  dependencies:
    - build-frontend
  variables:
    LABEL: 'dev'
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --target production
      --context services/objectstore-manager
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --cleanup
      --destination $CI_REGISTRY_IMAGE/objectstore-manager:$LABEL
    - rm -R /kaniko/2/opt/pysetup
    - /kaniko/executor
      --target production
      --context services/job-manager
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --cleanup
      --destination $CI_REGISTRY_IMAGE/job-manager:$LABEL
    - /kaniko/executor
      --context services/frontend
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --cleanup
      --destination $CI_REGISTRY_IMAGE/frontend:$LABEL
  when: manual

deploy-feature:
  stage: deploy
  needs:
    - build-frontend
    - build-frontend-image
    - job-manager-build
    - os-manager-build
  dependencies:
    - build-frontend
  variables:
    LABEL: 'feature'
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --target production
      --context services/objectstore-manager
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --cleanup
      --destination $CI_REGISTRY_IMAGE/objectstore-manager:$LABEL
    - rm -R /kaniko/2/opt/pysetup
    - /kaniko/executor
      --target production
      --context services/job-manager
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --cleanup
      --destination $CI_REGISTRY_IMAGE/job-manager:$LABEL
    - /kaniko/executor
      --context services/frontend
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --cleanup
      --destination $CI_REGISTRY_IMAGE/frontend:$LABEL
  when: manual

deploy-tag:
  stage: deploy
  needs:
    - build-frontend
    - build-frontend-image
    - job-manager-build
    - os-manager-build
  dependencies:
    - build-frontend
  variables:
    LABEL: $CI_COMMIT_TAG
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --target production
      --context services/objectstore-manager
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --cleanup
      --destination $CI_REGISTRY_IMAGE/objectstore-manager:$LABEL
    - rm -R /kaniko/2/opt/pysetup
    - /kaniko/executor
      --target production
      --context services/job-manager
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --cleanup
      --destination $CI_REGISTRY_IMAGE/job-manager:$LABEL
    - /kaniko/executor
      --context services/frontend
      --dockerfile Dockerfile
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --compressed-caching
      --cleanup
      --destination $CI_REGISTRY_IMAGE/frontend:$LABEL
  when: manual
  rules:
    - if: '$CI_COMMIT_TAG'