.build-test-and-lint:
  stage: test
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - /kaniko/executor
      --context "${BUILD_CONTEXT}"
      --dockerfile "$DOCKERFILE"
      --target lint
      --destination "$CI_REGISTRY_IMAGE/$IMG_NAME:lint"
    - docker push $CI_REGISTRY_IMAGE/$IMG_NAME:lint
    - /kaniko/executor
      --context "${BUILD_CONTEXT}"
      --dockerfile "$DOCKERFILE"
      --target test
      --destination "$CI_REGISTRY_IMAGE/$IMG_NAME:test"
    - docker push $CI_REGISTRY_IMAGE/$IMG_NAME:test
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
