.build-template:
  stage: build
  image: docker:20.10.17-dind
  when: on_success
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd $DIR
    - docker buildx build
      -f Dockerfile
      --cache-from $CI_REGISTRY_IMAGE/$IMG_NAME:$LABEL
      --tag $CI_REGISTRY_IMAGE/$IMG_NAME:$LABEL
      --build-arg BUILDKIT_INLINE_CACHE=1
      --build-context templates="../../"
      "."
    - docker push $CI_REGISTRY_IMAGE/$IMG_NAME:$LABEL
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    LABEL: $CI_COMMIT_REF_NAME
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "main"'
      variables:
        LABEL: "latest"
      changes:
        - $DIR/**/*
    - if: '$CI_COMMIT_BRANCH == "main"'
      variables:
        LABEL: "latest"
      changes:
        - $DIR/**/*
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH'
      changes:
        - $DIR/**/*
    - if: '$CI_COMMIT_TAG'
      variables:
        LABEL: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH'
