apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shepard
  labels:
    app: shepard
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shepard
      tier: backend
      name: shepard-backend
  template:
    metadata:
      labels:
        app: shepard
        tier: backend
        name: shepard-backend
    spec:
      containers:
        - name: backend
          image: "registry.gitlab.com/dlr-shepard/backend:2022.03.821dev"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: api
          env:
            - name: CATALINA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: shepard-backend
                  key: catalinaOpts
            - name: oidc.public
              valueFrom:
                configMapKeyRef:
                  name: shepard-backend
                  key: oidcPublic
            - name: oidc.authority
              valueFrom:
                configMapKeyRef:
                  name: shepard-backend
                  key: oidcAuthority
            - name: influx.host
              valueFrom:
                configMapKeyRef:
                  name: shepard-backend
                  key: influxHost
            - name: influx.username
              valueFrom:
                configMapKeyRef:
                  name: shepard-backend
                  key: influxUsername
            - name: influx.password
              valueFrom:
                configMapKeyRef:
                  name: shepard-backend
                  key: influxPassword
            - name: neo4j.host
              valueFrom:
                configMapKeyRef:
                  name: shepard-backend
                  key: neo4jHost
            - name: neo4j.username
              valueFrom:
                configMapKeyRef:
                  name: shepard-backend
                  key: neo4jUsername
            - name: neo4j.password
              valueFrom:
                configMapKeyRef:
                  name: shepard-backend
                  key: neo4jPassword
            - name: mongo.host
              valueFrom:
                configMapKeyRef:
                  name: shepard-backend
                  key: mongoHost
            - name: mongo.username
              valueFrom:
                configMapKeyRef:
                  name: shepard-backend
                  key: mongoUsername
            - name: mongo.password
              valueFrom:
                configMapKeyRef:
                  name: shepard-backend
                  key: mongoPassword
      serviceAccountName: default-shepard