apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: shepard
  labels:
    app: shepard
    name: shepard-service
    tier: backend
spec:
  selector:
    app: shepard
    name: shepard-backend
    tier: backend
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP