openapi: 3.0.3
info:
  title: Job Manager
  description: Job Manager
  version: 1.0.0
servers:
  - url: 'http://jobmanager.os4ml.svc.cluster.local:8000'
paths:
  "/apis/v1beta1/jobmanager/runs/{solverName}":
    post:
      summary: 'Create a run by solver name'
      operationId: createRunBySolverName
      parameters:
        - $ref: '#/components/parameters/SolverName'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      tags:
        - jobmanager
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RunParams"
      responses:
        201:
          description: "Resource created"
          content:
            application/json:
              schema:
                $ref: './shared-oas.yaml#/components/schemas/RunId'

  "/apis/v1beta1/jobmanager/runs/{runId}":
    get:
      summary: 'Get a run by id'
      operationId: getRunById
      parameters:
        - $ref: '#/components/parameters/RunId'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      tags:
        - jobmanager
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Run'
        404:
          $ref: '#/components/responses/NotFound'
    put:
      summary: 'Terminate a run'
      operationId: terminateRunById
      parameters:
        - $ref: '#/components/parameters/RunId'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      tags:
        - jobmanager
      responses:
        200:
          description: Terminated

components:
  schemas:
    OIDCUser:
      $ref: './shared-oas.yaml#/components/schemas/OIDCUser'
    User:
      $ref: './shared-oas.yaml#/components/schemas/User'
    ExperimentId:
      type: string
    PipelineId:
      type: string
    Experiment:
      description: Experiment Object
      type: object
      required:
        - name
      properties:
        id:
          $ref: '#/components/schemas/ExperimentId'
        name:
          type: string
        description:
          type: string
    Pipeline:
      description: Pipeline Object
      type: object
      required:
        - name
        - description
      properties:
        id:
          $ref: '#/components/schemas/PipelineId'
        name:
          type: string
        description:
          type: string
    CreatePipeline:
      description: Create Pipeline Object
      allOf:
        - $ref: '#/components/schemas/Pipeline'
        - type: object
          required:
            - config_url
          properties:
            configUrl:
              type: string
    Metrics:
      description: Run Metrics
      type: object
      properties:
        name:
          type: string
        value:
          type: number
        format:
          type: string
    Run:
      description: Run Object
      type: object
      required:
        - name
      properties:
        id:
          $ref: './shared-oas.yaml#/components/schemas/RunId'
        name:
          type: string
        status:
          type: string
        error:
          type: string
        metrics:
          type: array
          items:
            $ref: '#/components/schemas/Metrics'
    RunParams:
      description: Parameters to start a run
      type: object
      properties:
        databagId:
          type: string
        solutionId:
          type: string
        predictionId:
          type: string
    CreateRun:
      description: Create Run Object
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        params:
          $ref: "#/components/schemas/RunParams"
    Error:
      required:
        - path
        - error
        - timestamp
        - message
        - status

  parameters:
    ExperimentId:
      name: experimentId
      in: path
      description: Id of Experiment
      required: true
      schema:
        $ref: '#/components/schemas/ExperimentId'
    PipelineId:
      name: pipelineId
      in: path
      description: Id of Pipeline
      required: true
      schema:
        $ref: '#/components/schemas/PipelineId'
    RunId:
      name: runId
      in: path
      description: Id of Run
      required: true
      schema:
        $ref: './shared-oas.yaml#/components/schemas/RunId'
    PipelineTemplateName:
      name: pipelineTemplateName
      in: path
      description: Name of the PipelineTemplate
      required: true
      schema:
        type: string
    SolutionName:
      name: solutionName
      in: path
      description: Name of the Solution
      required: true
      schema:
        type: string
    SolverName:
      name: solverName
      in: path
      description: Name of the solver
      required: true
      schema:
        type: string
  responses:
    Created:
      description: New resource created
    Deleted:
      description: The specified resource was deleted
    Updated:
      description: The specified resource was updated
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    RequestBodyMismatch:
      description: The provided request body has the wrong format
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    RequestBodyInvalid:
      description: The content of the request body is invalid
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
