openapi: 3.0.3
info:
  title: Shared OAS
  description: Shared OAS
  version: 1.0.0

paths: {}

components:
  parameters:
    User:
      name: usertoken
      in: header
      schema:
        type: string
  schemas:
    RunId:
      type: string
    DatabagId:
      type: string
    Solver:
      properties:
        name:
          type: string
        type:
          type: string
        description:
          type: string
        pipelineStep:
          type: string
    PipelineTemplate:
      properties:
        name:
          type: string
        type:
          type: string
        description:
          type: string
        pipelineStep:
          type: string
        fileUrl:
          type: string
    Solution:
      properties:
        name:
          type: string
        status:
          type: string
          nullable: true
        solver:
          type: string
        databagName:
          type: string
        databagId:
          $ref: "#/components/schemas/DatabagId"
        inputFields:
          type: array
          items:
            type: string
        outputFields:
          type: array
          items:
            type: string
        runId:
          $ref: '#/components/schemas/RunId'
        creationTime:
          type: string
        completionTime:
          type: string
          nullable: true
        metrics:
          type: array
          items:
            $ref: '#/components/schemas/Metric'
    Metric:
      properties:
        name:
          type: string
        value:
          type: number
    Column:
      properties:
        name:
          type: string
        type:
          type: string
        numEntries:
          type: integer
    Databag:
      properties:
        datasetType:
          type: string
          nullable: true
        fileName:
          type: string
          nullable: true
        databagName:
          type: string
        databagId:
          $ref: "#/components/schemas/DatabagId"
          nullable: true
        numberRows:
          type: integer
          nullable: true
        numberColumns:
          type: integer
          nullable: true
        columns:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/Column"
        creationTime:
          type: string
          nullable: true
        status:
          type: string
          nullable: true
        runId:
          type: string
          nullable: true
    JsonResponse:
      properties:
        jsonContent:
          type: string
          format: byte
    User:
      type: object
      required:
        - id
        - email
        - rawToken
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        rawToken:
          type: string
          format: byte
    OIDCUser:
      type: object
      required:
        - sub
        - iat
        - exp
        - scope
        - email_verified
        - realm_access
        - resource_access
        - extra_fields
      properties:
        sub:
          type: string
        iat:
          type: integer
        exp:
          type: integer
        scope:
          type: string
        email_verified:
          type: boolean
        name:
          type: string
        given_name:
          type: string
        family_name:
          type: string
        email:
          type: string
        preferred_username:
          type: string
        realm_access:
          type: object
        resource_access:
          type: object
        extra_fields:
          type: object

