apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: os4ml-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: false
      hosts:
        - "*"