apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shepard
  labels:
    app: shepard
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shepard
      tier: frontend
      name: shepard-frontend
  template:
    metadata:
      labels:
        app: shepard
        tier: frontend
        name: shepard-frontend
    spec:
      containers:
        - name: backend
          image: "registry.gitlab.com/dlr-shepard/frontend:2022.03.540dev"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          env:
            - name: VUE_APP_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: shepard-frontend
                  key: vueAppBackend
            - name: VUE_APP_OIDC_AUTHORITY
              valueFrom:
                configMapKeyRef:
                  name: shepard-frontend
                  key: vueAppOidcAuth
            - name: VUE_APP_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: shepard-frontend
                  key: vueAppClientId
          resources:
            limits:
              cpu: 250m
              memory: 500Mi