e2e:
  stage: e2e
  needs:
    - deploy-testing
  image: $CI_REGISTRY/developer/images/gitlab-terraform-gcloud-kubectl:gcloud387-terraform1.2
  before_script:
    - gcloud auth activate-service-account $GCP_service_account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
    - gcloud container clusters get-credentials $GCP_cluster_name --zone=$GCP_zone --project=$GCP_project
  script:
    - wget https://github.com/minio/operator/releases/download/v4.4.16/kubectl-minio_4.4.16_linux_amd64 -O kubectl-minio && chmod +x kubectl-minio && mv kubectl-minio /usr/local/bin/
    - kubectl minio tenant delete storage-testing --namespace minio-tenant-testing --force
    - export NODE_VERSION=v16.17.0 && export NODE_DISTRO=linux-x64 && wget https://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION-$NODE_DISTRO.tar.xz && mkdir -p /usr/local/lib/nodejs && tar -xJvf node-$NODE_VERSION-$NODE_DISTRO.tar.xz -C /usr/local/lib/nodejs && export PATH=/usr/local/lib/nodejs/node-$VERSION-$DISTRO/bin:$PATH && . ~/.profile
    - curl -qL https://www.npmjs.com/install.sh | sh
    - cd services/frontend && npm install && npm run cypress run
