stages:
  - e2e

.cypress_base:
  image: cypress/browsers:latest
  tags:
    - aime
  stage: e2e
  needs:
    - reset
  artifacts:
    when: always
    paths:
      - services/frontend/cypress/videos/**/*.mp4
      - services/frontend/cypress/screenshots/**/*.png
    expire_in: 1 day
  resource_group: testing
  retry: 1
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE
      when: delayed
      start_in: 30 seconds

root_page_test:
  extends: .cypress_base
  script:
    - cd services/frontend && npm ci && npx cypress run --spec 'cypress/e2e/root-page.spec.cy.ts' --browser chrome

databags_page_test:
  extends: .cypress_base
  script:
    - cd services/frontend && npm ci && npx cypress run --spec 'cypress/e2e/databags-page.spec.cy.ts' --browser chrome

solutions_page_test:
  extends: .cypress_base
  script:
    - cd services/frontend && npm ci && npx cypress run --spec 'cypress/e2e/solutions-page.spec.cy.ts' --browser chrome

predictions_page_test:
  extends: .cypress_base
  script:
    - cd services/frontend && npm ci && npx cypress run --spec 'cypress/e2e/predictions-page.spec.cy.ts' --browser chrome
