include:
  - local: 'gitlab/shared/.gitlab-ci.build-test.yml'

validate-templates:
  extends:
    - .build-development
  variables:
    DOCKERFILE: 'templates/Dockerfile'
    IMG_NAME: 'templates'
    BUILD_CONTEXT: 'templates'