reset-testing:
  stage: reset
  needs:
    - deploy-testing
  resource_group: testing
  trigger:
    include: gitlab/.gitlab-ci.e2e.yml
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
