.deploy:
  stage: deploy
  services:
    - name: docker:20.10.14-dind
      command: ["--registry-mirror", "http://172.16.10.15:5000", "--registry-mirror", "http://172.16.10.15:5001"]  # Specify the registry mirror to use
  image: docker:20.10.14
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
  needs:
    - build-frontend
    - build-frontend-image
    - job-manager-build
    - os-manager-build
    - build-python
    - build-pandas
    - build-ludwig
  script:
    - docker pull $CI_REGISTRY_IMAGE/objectstore-manager:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/objectstore-manager:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/objectstore-manager:$LABEL
    - docker push $CI_REGISTRY_IMAGE/objectstore-manager:$LABEL
    - docker build
      -f 'services/job-manager/Dockerfile'
      --target production
      --cache-from $CI_REGISTRY_IMAGE/job-manager:$CI_COMMIT_SHA
      --tag $CI_REGISTRY_IMAGE/job-manager:$LABEL
      --build-arg BUILDKIT_INLINE_CACHE=1
      --build-arg IMAGE_TAG=$LABEL
      '.'
    - docker push $CI_REGISTRY_IMAGE/job-manager:$LABEL
    - docker pull $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/frontend:$LABEL
    - docker push $CI_REGISTRY_IMAGE/frontend:$LABEL
    - docker pull $CI_REGISTRY_IMAGE/python:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/python:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/python:$LABEL
    - docker push $CI_REGISTRY_IMAGE/python:$LABEL
    - docker pull $CI_REGISTRY_IMAGE/pandas:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/pandas:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/pandas:$LABEL
    - docker push $CI_REGISTRY_IMAGE/pandas:$LABEL
    - docker pull $CI_REGISTRY_IMAGE/ludwig:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/ludwig:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/ludwig:$LABEL
    - docker push $CI_REGISTRY_IMAGE/ludwig:$LABEL

deploy-tag:
  extends:
    - .deploy
  variables:
    LABEL: $CI_COMMIT_TAG
  when: manual
  rules:
    - if: '$CI_COMMIT_TAG'

deploy-prod:
  extends:
    - .deploy
  variables:
    LABEL: 'latest'
  when: manual
  rules:
    - if: '$CI_COMMIT_TAG'

deploy-staging:
  extends:
    - .deploy
  variables:
    LABEL: 'stage'
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: $CI_COMMIT_REF_NAME =~ /^hotfix/
    - if: '$CI_COMMIT_TAG'

deploy-release:
  extends:
    - .deploy
  variables:
    LABEL: 'rc'
  when: manual
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^rc/
    - if: $CI_COMMIT_REF_NAME =~ /^release/

deploy-dev:
  extends:
    - .deploy
  variables:
    LABEL: 'dev'
  when: manual

deploy-feature:
  extends:
    - .deploy
  variables:
    LABEL: 'feature'
  when: manual

deploy-testing:
  extends:
    - .deploy
  variables:
    LABEL: 'testing'
  when: manual
