include:
  - local: 'gitlab/shared/.gitlab-ci.build-images.yml'

build-python:
  extends:
    - .build-production
  variables:
    BUILD_CONTEXT: 'templates'
    IMG_NAME: 'python'
    DOCKERFILE: 'templates/dockerfiles/python/Dockerfile'

build-pandas:
  extends:
    - .build-production
  variables:
    BUILD_CONTEXT: 'templates'
    IMG_NAME: 'pandas'
    DOCKERFILE: 'templates/dockerfiles/pandas/Dockerfile'

build-ludwig:
  extends:
    - .build-production
  variables:
    BUILD_CONTEXT: 'templates'
    IMG_NAME: 'ludwig'
    DOCKERFILE: 'templates/dockerfiles/ludwig/Dockerfile'
