enas-trial-build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - cd $DIR
    - /kaniko/executor
      --target production
      --context $DIR
      --dockerfile $DOCKERFILE
      --destination $CI_REGISTRY_IMAGE/$IMG_NAME:$LABEL
  when: on_success
  variables:
    DOCKER_DRIVER: overlay2
    DIR: 'templates/dockerfiles/enas-trial'
    IMG_NAME: 'enas-trial'
    LABEL: $CI_COMMIT_SHORT_SHA
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "main"'
      variables:
        LABEL: "latest"
      changes:
        - $DIR/**/*
    - if: '$CI_COMMIT_BRANCH == "main"'
      variables:
        LABEL: "latest"
      changes:
        - $DIR/**/*
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH'
      changes:
        - $DIR/**/*
    - if: '$CI_COMMIT_TAG'
      variables:
        LABEL: $CI_COMMIT_TAG
