include:
  - local: 'gitlab/shared/.gitlab-ci.build-production.yml'
  - local: 'gitlab/shared/.gitlab-ci.build-test-and-lint.yml'

templates-test-and-lint:
  extends:
    - .build-test-and-lint
  variables:
    DOCKERFILE: 'templates/Dockerfile'
    IMG_NAME: 'templates'
    BUILD_CONTEXT: 'templates'

build-python:
  extends:
    - .build-production
  needs:
    - templates-test-and-lint
  variables:
    BUILD_CONTEXT: 'templates'
    IMG_NAME: 'os4ml-python'
    DOCKERFILE: 'templates/dockerfiles/python/Dockerfile'
    IMAGE_REGISTRY: 'wogra'

build-pandas:
  extends:
    - .build-production
  needs:
    - templates-test-and-lint
  variables:
    BUILD_CONTEXT: 'templates'
    IMG_NAME: 'os4ml-pandas'
    DOCKERFILE: 'templates/dockerfiles/pandas/Dockerfile'
    IMAGE_REGISTRY: 'wogra'

build-ludwig:
  extends:
    - .build-production
  needs:
    - templates-test-and-lint
  variables:
    BUILD_CONTEXT: 'templates'
    IMG_NAME: 'os4ml-ludwig'
    DOCKERFILE: 'templates/dockerfiles/ludwig/Dockerfile'
    IMAGE_REGISTRY: 'wogra'
