e2e:
  image: cypress/browsers:node18.12.0-chrome103-ff107
  tags:
    - aime
  stage: e2e
  needs:
    - reset
  script:
    - cd services/frontend && npm ci && npx cypress run --browser chrome
  artifacts:
    when: always
    paths:
      - services/frontend/cypress/videos/**/*.mp4
      - services/frontend/cypress/screenshots/**/*.png
    expire_in: 1 day
  resource_group: testing
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
