enas-trial-build:
  stage: build
  image: docker:19.03.13-dind
  when: on_success
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd $DIR
    - docker build
      --cache-from $CI_REGISTRY_IMAGE/$IMG_NAME:$LABEL
      --tag $CI_REGISTRY_IMAGE/$IMG_NAME:$LABEL
      --build-arg BUILDKIT_INLINE_CACHE=1
      "."
    - docker push $CI_REGISTRY_IMAGE/$IMG_NAME:$LABEL
    - echo $CI_REGISTRY_IMAGE/$IMG_NAME:$LABEL
  variables:
    DOCKER_DRIVER: overlay2
    DIR: 'templates/dockerfiles/enas-trial'
    IMG_NAME: 'enas-trial'
    DOCKER_BUILDKIT: 1
    LABEL: $CI_COMMIT_SHORT_SHA
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "main"'
      variables:
        LABEL: "latest"
      changes:
        - $DIR/**/*
    - if: '$CI_COMMIT_BRANCH == "main"'
      variables:
        LABEL: "latest"
      changes:
        - $DIR/**/*
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH'
      changes:
        - $DIR/**/*
    - if: '$CI_COMMIT_TAG'
      variables:
        LABEL: $CI_COMMIT_TAG
