include:
  - local: 'gitlab/shared/.gitlab-ci.build-production.yml'
  - local: 'gitlab/shared/.gitlab-ci.build-test-and-lint.yml'

templates-test:
  extends:
    - .build-test
  variables:
    DOCKERFILE: 'templates/Dockerfile'
    IMG_NAME: 'templates'
    BUILD_CONTEXT: 'templates'

templates-lint:
  extends:
    - .build-lint
  variables:
    DOCKERFILE: 'templates/Dockerfile'
    IMG_NAME: 'templates'
    BUILD_CONTEXT: 'templates'

build-python:
  extends:
    - .build-production
  needs:
    - templates-test
    - templates-lint
  variables:
    BUILD_CONTEXT: 'templates'
    IMG_NAME: 'python'
    DOCKERFILE: 'templates/dockerfiles/python/Dockerfile'

build-pandas:
  extends:
    - .build-production
  needs:
    - templates-test
    - templates-lint
  variables:
    BUILD_CONTEXT: 'templates'
    IMG_NAME: 'pandas'
    DOCKERFILE: 'templates/dockerfiles/pandas/Dockerfile'

build-ludwig:
  extends:
    - .build-production
  needs:
    - templates-test
    - templates-lint
  variables:
    BUILD_CONTEXT: 'templates'
    IMG_NAME: 'ludwig'
    DOCKERFILE: 'templates/dockerfiles/ludwig/Dockerfile'
