e2e:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: e2e
  needs:
    - reset
  script:
    - cd services/frontend && npm ci && npx cypress run
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day
