e2e:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  tags:
    - aime
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: "reset-testing"
  script:
    - cd services/frontend && npm ci && npx cypress run
  artifacts:
    when: always
    paths:
      - services/frontend/cypress/videos/**/*.mp4
      - services/frontend/cypress/screenshots/**/*.png
    expire_in: 1 day
