e2e:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  tags:
    - aime
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: "reset-testing"
  script:
    - cd services/frontend && npm ci && npx cypress run
  artifacts:
    when: always
    paths:
      - services/frontend/cypress/videos/**/*.mp4
      - services/frontend/cypress/screenshots/**/*.png
    expire_in: 1 day

reset-test:
  tags:
    - aime
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: "reset-testing"
  image: $CI_REGISTRY/developer/images/gitlab-terraform-gcloud-kubectl:gcloud387-terraform1.2
  before_script:
    - gcloud auth activate-service-account $GCP_service_account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
    - gcloud container clusters get-credentials $GCP_cluster_name --zone=$GCP_zone --project=$GCP_project
  script:
    - wget https://github.com/minio/operator/releases/download/v4.4.16/kubectl-minio_4.4.16_linux_amd64 -O kubectl-minio && chmod +x kubectl-minio && mv kubectl-minio /usr/local/bin/
    - kubectl minio tenant delete storage-testing --namespace minio-tenant-testing --force
    - kubectl delete pvc --namespace minio-tenant-testing data0-storage-testing-pool-0-0 --force
