apiVersion: v1
kind: Service
metadata:
  name: objectstore-manager
  namespace: os4ml
  labels:
    app: objectstore-manager
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
      targetPort: http
      name: api
  selector:
    app: objectstore-manager