apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend
spec:
  gateways:
    - os4ml-gateway
    - kubeflow/kubeflow-gateway
  hosts:
    - '*'
  http:
    - name: "frontend-route"
      match:
        - uri:
            prefix: /os4ml/
      rewrite:
        uri: /
      route:
        - destination:
            host: frontend.os4ml.svc.cluster.local
            port:
              number: 80
