apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: os4ml-ui
  namespace: os4ml
spec:
  gateways:
    - os4ml/os4ml-gateway
  hosts:
    - '*'
  http:
    - name: "frontend-route"
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: os4ml-ui.os4ml.svc.cluster.local
            port:
              number: 80
