apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: os4ml-ui
  namespace: os4ml
spec:
  gateways:
    - os4ml/os4ml-gateway
  hosts:
    - 'os4ml.wogra.com'
  http:
    - name: "frontend-route"
      match:
        - uri:
            prefix: /os4ml/
      rewrite:
        uri: /
      route:
        - destination:
            host: os4ml-ui.os4ml.svc.cluster.local
            port:
              number: 80
