# coding: utf-8

from datetime import date, datetime
from typing import Dict, List, Optional

from fastapi_utils.api_model import APIModel
from pydantic import BaseModel, EmailStr, validator


class SolutionMetrics(APIModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SolutionMetrics - a model defined in OpenAPI

        accuracy: The accuracy of this SolutionMetrics [Optional].
    """

    accuracy: Optional[float] = None
