# coding: utf-8

from datetime import date, datetime

from typing import Dict, List, Optional
from pydantic import BaseModel, EmailStr, validator
from build.openapi_server.models.solution_metrics import SolutionMetrics
from fastapi_utils.api_model import APIModel


class Solution(APIModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Solution - a model defined in OpenAPI

        name: The name of this Solution [Optional].
        status: The status of this Solution [Optional].
        error_msg_key: The error_msg_key of this Solution [Optional].
        solver: The solver of this Solution [Optional].
        databag_name: The databag_name of this Solution [Optional].
        databag_id: The databag_id of this Solution [Optional].
        input_fields: The input_fields of this Solution [Optional].
        output_fields: The output_fields of this Solution [Optional].
        run_id: The run_id of this Solution [Optional].
        creation_time: The creation_time of this Solution [Optional].
        completion_time: The completion_time of this Solution [Optional].
        metrics: The metrics of this Solution [Optional].
    """

    name: Optional[str] = None
    status: Optional[str] = None
    error_msg_key: Optional[str] = None
    solver: Optional[str] = None
    databag_name: Optional[str] = None
    databag_id: Optional[str] = None
    input_fields: Optional[List[str]] = None
    output_fields: Optional[List[str]] = None
    run_id: Optional[str] = None
    creation_time: Optional[str] = None
    completion_time: Optional[str] = None
    metrics: Optional[SolutionMetrics] = None
