from fastapi_utils.api_model import APIModel


class Solver(APIModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Solver - a model defined in OpenAPI

        name: The name of this Solver [Optional].
        type: The type of this Solver [Optional].
        description: The description of this Solver [Optional].
        pipeline_step: The pipeline_step of this Solver [Optional].
    """

    name: str | None = None
    type: str | None = None
    description: str | None = None
    pipeline_step: str | None = None
