apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-tenant
commonLabels:
  app: minio
resources:
  - namespace.yaml
  - tenant-config.yaml
  - storage-creds-secret.yaml
  - storage-user.yaml
  - tenant.yaml