apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-translator
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: os4ml
      app.kubernetes.io/component: workflow-translator
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: os4ml
        app.kubernetes.io/component: workflow-translator
    spec:
      containers:
        - name: workflow-translator
          image: "wogra/os4ml-workflow-translator"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          env:
            - name: WORKFLOW_ENGINE
              valueFrom:
                configMapKeyRef:
                  name: workflow-translator-config
                  key: engine
            - name: OS4ML_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: workflow-translator-config
                  key: os4mlNS
            - name: PREPARE_NODE_SELECTOR
              valueFrom:
                configMapKeyRef:
                  name: workflow-translator-config
                  key: prepareNodeSelector
            - name: PREPARE_NODE_TOLERATION
              valueFrom:
                configMapKeyRef:
                  name: workflow-translator-config
                  key: prepareNodeToleration
            - name: SOLVE_NODE_SELECTOR
              valueFrom:
                configMapKeyRef:
                  name: workflow-translator-config
                  key: solveNodeSelector
            - name: SOLVE_NODE_TOLERATION
              valueFrom:
                configMapKeyRef:
                  name: workflow-translator-config
                  key: solveNodeToleration
            - name: APPLY_NODE_SELECTOR
              valueFrom:
                configMapKeyRef:
                  name: workflow-translator-config
                  key: applyNodeSelector
            - name: APPLY_NODE_TOLERATION
              valueFrom:
                configMapKeyRef:
                  name: workflow-translator-config
                  key: applyNodeToleration
          resources:
            limits:
              cpu: 500m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          startupProbe:
            httpGet:
              port: http
              path: /docs
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: http
              path: /docs
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 4
          livenessProbe:
            httpGet:
              port: http
              path: /docs
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 4
          securityContext:
            allowPrivilegeEscalation: false
      serviceAccountName: service-account
      imagePullSecrets:
        - name: registry-credentials
