apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-translator
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: os4ml
      name: workflow-translator
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: os4ml
        name: workflow-translator
    spec:
      containers:
        - name: workflow-translator
          image: "gitlab-registry.wogra.com/developer/wogra/os4ml/workflow-translator"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          env:
            - name: WORKFLOW_ENGINE
              valueFrom:
                configMapKeyRef:
                  name: workflow-translator-config
                  key: engine
            - name: OS4ML_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: workflow-translator-config
                  key: os4mlNS
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 100m
              memory: 200Mi
          readinessProbe:
            httpGet:
              port: http
              path: /docs
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
      serviceAccountName: service-account
      imagePullSecrets:
        - name: registry-credentials