apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: "gitlab-registry.wogra.com/developer/images/os4ml:latest"
    newName: "gitlab-registry.wogra.com/developer/images/os4ml"
    newTag: latest
