openapi: 3.0.3
info:
  title: Shared OAS
  description: Shared OAS
  version: 1.0.0

paths: {}

components:
  parameters:
    User:
      name: usertoken
      in: header
      schema:
        type: string
  schemas:
    UserId:
      type: string
    UserIdObject:
      properties:
        userId:
          $ref: '#/components/schemas/UserId'
    RunId:
      type: string
    DatabagId:
      type: string
    SolutionId:
      type: string
    PredictionId:
      type: string
    TransferLearningModelId:
      type: string
    Url:
      type: string
      nullable: true
    DatabagType:
      type: string
      enum:
        - local_file
        - file_url
    Databag:
      properties:
        id:
          $ref: "#/components/schemas/DatabagId"
          nullable: true
        name:
          type: string
        status:
          type: string
          nullable: true
        runId:
          $ref: '#/components/schemas/RunId'
          nullable: true
        creationTime:
          type: string
          nullable: true
        completionTime:
          type: string
          nullable: true
        databagType:
          type: string
          nullable: true
        numberRows:
          type: integer
          nullable: true
        numberColumns:
          type: integer
          nullable: true
        columns:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/Column"
        datasetFileName:
          type: string
          nullable: true
        datasetUrl:
          $ref: '#/components/schemas/Url'
          nullable: true
    Solution:
      properties:
        id:
          $ref: '#/components/schemas/SolutionId'
          nullable: true
        name:
          type: string
        status:
          type: string
          nullable: true
        runId:
          $ref: '#/components/schemas/RunId'
          nullable: true
        creationTime:
          type: string
        completionTime:
          type: string
          nullable: true
        solver:
          type: string
        databagId:
          $ref: "#/components/schemas/DatabagId"
        inputFields:
          type: array
          items:
            type: string
        outputFields:
          type: array
          items:
            type: string
        metrics:
          nullable: true
          $ref: '#/components/schemas/Metrics'
        predictionTemplateFileName:
          type: string
          nullable: true
        transferLearningSettings:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/TransferLearningSetting"
    Prediction:
      properties:
        id:
          $ref: '#/components/schemas/PredictionId'
          nullable: true
        name:
          type: string
        status:
          type: string
          nullable: true
        runId:
          $ref: '#/components/schemas/RunId'
          nullable: true
        creationTime:
          type: string
          nullable: true
        completionTime:
          type: string
          nullable: true
        databagId:
          $ref: '#/components/schemas/DatabagId'
        solutionId:
          $ref: '#/components/schemas/SolutionId'
        dataFileName:
          type: string
          nullable: true
        dataUrl:
          $ref: '#/components/schemas/Url'
          nullable: true
    TransferLearningModel:
      required:
        - name
        - type
      properties:
        id:
          $ref: '#/components/schemas/TransferLearningModelId'
          nullable: true
        name:
          type: string
        type:
          type: string
        origin:
          type: string
        value:
          type: string
        sharedWith:
          nullable: true
          type: array
          items:
            $ref: '#/components/schemas/UserId'
    PipelineStep:
      type: string
      enum:
        - prepare
        - solve
        - apply
    Solver:
      properties:
        name:
          type: string
        type:
          type: string
        description:
          type: string
        pipelineStep:
          type: string
    Metrics:
      type: object
      nullable: true
      properties:
        combined:
          type: number
        details:
          type: array
          items:
            $ref: '#/components/schemas/Metric'
    Metric:
      properties:
        outputField:
          type: string
        name:
          type: string
        value:
          type: number
    Column:
      properties:
        name:
          type: string
        type:
          type: string
        numEntries:
          type: integer
    TransferLearningSetting:
      required:
        - name
        - type
        - selectedTransferLearningModel
      properties:
        name:
          type: string
        type:
          type: string
        selectedTransferLearningModel:
          $ref: '#/components/schemas/TransferLearningModel'
    NewTransferLearningModelDto:
      required:
        - name
        - solutionId
        - selectedSolutionInput
      properties:
        name:
          type: string
        solutionId:
          type: string
        selectedSolutionInput:
          type: string
    JsonResponse:
      properties:
        jsonContent:
          type: string
          format: byte
    User:
      type: object
      required:
        - id
        - email
        - rawToken
      properties:
        id:
          $ref: '#/components/schemas/UserId'
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        rawToken:
          type: string
          format: byte
    OIDCUser:
      type: object
      required:
        - sub
        - iat
        - exp
        - scope
        - email_verified
        - realm_access
        - resource_access
        - extra_fields
      properties:
        sub:
          type: string
        iat:
          type: integer
        exp:
          type: integer
        scope:
          type: string
        email_verified:
          type: boolean
        name:
          type: string
        given_name:
          type: string
        family_name:
          type: string
        email:
          type: string
        preferred_username:
          type: string
        realm_access:
          type: object
        resource_access:
          type: object
        extra_fields:
          type: object

