[tool.poetry]
name = "gbi-genios_event_detection"
version = "0.1.0"
description = ""
authors = ["thomasf <tf@wogra.com>", "Dominik Koziol <dk@wogra.com>"]

[tool.poetry.dependencies]
python = "~3.7.9"
python-dotenv = "^0.15.0"
dulwich = "!=0.20.19"
pandas = "^1.1"
dvc = "^1.11"
openpyxl = "^3.0"
tables = "^3.6"
xlwt = "^1.3"
xlrd = "^2.0"
boto3 = "^1.16.37"
pytest = "^6.2.1"
joblib = "^1.0.0"
ludwig = {version = "^0.3.1", extras = ["text"]}
scikit-learn = "^0.24.0"
seaborn = "^0.11.1"
fastapi = "^0.63.0"
uvicorn = "^0.13.3"
dask = {version = "^2021.2.0", extras = ["complete"]}

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
pytest = "^6.2.1"
pytest-mock = "^3.5.1"
pytest-flake8 = "^1.0.7"
fastapi-code-generator ="^0.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

