openapi: 3.0.3
info:
  title: Model Manager
  description: Model Manager
  version: 1.0.0
servers:
  - url: 'http://model-manager.os4ml.svc.cluster.local:8000'
paths:
  "/apis/v1beta1/model-manager/databags":
    get:
      summary: "get databags"
      operationId: getDatabags
      tags:
        - modelmanager
      parameters:
        - $ref: './shared-oas.yaml#/components/parameters/User'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './shared-oas.yaml#/components/schemas/Databag'
    post:
      summary: "create databag"
      operationId: createDatabag
      tags:
        - modelmanager
      parameters:
        - $ref: './shared-oas.yaml#/components/parameters/User'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './shared-oas.yaml#/components/schemas/Databag'
      responses:
        201:
          description: "Resource created"
          content:
            application/json:
              schema:
                $ref: './shared-oas.yaml#/components/schemas/Databag'

  "/apis/v1beta1/model-manager/databags/{databagId}":
    get:
      summary: "get databag by id"
      operationId: getDatabagById
      tags:
        - modelmanager
      parameters:
        - $ref: '#/components/parameters/DatabagId'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './shared-oas.yaml#/components/schemas/Databag'
        404:
          $ref: '#/components/responses/NotFound'
    put:
      summary: "update databag"
      operationId: updateDatabagById
      tags:
        - modelmanager
      parameters:
        - $ref: '#/components/parameters/DatabagId'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './shared-oas.yaml#/components/schemas/Databag'
      responses:
        200:
          description: "Databag updated"
          content:
            application/json:
              schema:
                $ref: './shared-oas.yaml#/components/schemas/Databag'
    delete:
      summary: "delete Databag"
      operationId: deleteDatabagById
      tags:
        - modelmanager
      parameters:
        - $ref: '#/components/parameters/DatabagId'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      responses:
        204:
          $ref: '#/components/responses/Deleted'

  "/apis/v1beta1/model-manager/databags/dataset/{fileName}":
    get:
      summary: "get put url for dataset and get databagId for the databag"
      operationId: getDatasetPutUrl
      tags:
        - modelmanager
      parameters:
        - $ref: '#/components/parameters/FileName'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetPutUrl'

  "/apis/v1beta1/model-manager/databags/{databagId}/dataframe":
    get:
      summary: "get put url for dataframe of the databag"
      operationId: getDataframePutUrl
      tags:
        - modelmanager
      parameters:
        - $ref: '#/components/parameters/DatabagId'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      responses:
        200:
          $ref: '#/components/responses/PutUrlResponse'

  "/apis/v1beta1/model-manager/solvers":
    get:
      summary: 'get solvers'
      operationId: getSolvers
      tags:
        - modelmanager
      parameters:
        - $ref: './shared-oas.yaml#/components/parameters/User'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './shared-oas.yaml#/components/schemas/Solver'

  "/apis/v1beta1/model-manager/solvers/{solverName}":
    get:
      summary: 'get solver by name'
      operationId: getSolverByName
      parameters:
        - $ref: '#/components/parameters/SolverName'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      tags:
        - modelmanager
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './shared-oas.yaml#/components/schemas/Solver'
        404:
          $ref: '#/components/responses/NotFound'

  "/apis/v1beta1/model-manager/solutions":
    get:
      summary: 'get all solutions'
      operationId: getSolutions
      parameters:
        - $ref: './shared-oas.yaml#/components/parameters/User'
      tags:
        - modelmanager
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './shared-oas.yaml#/components/schemas/Solution'
    post:
      summary: "Create a Solution"
      operationId: createSolution
      parameters:
        - $ref: './shared-oas.yaml#/components/parameters/User'
      tags:
        - modelmanager
      requestBody:
        content:
          application/json:
            schema:
              $ref: './shared-oas.yaml#/components/schemas/Solution'
      responses:
        201:
          description: "Solution created"
          content:
            application/json:
              schema:
                $ref: './shared-oas.yaml#/components/schemas/Solution'

  "/apis/v1beta1/model-manager/solutions/{solutionId}":
    get:
      summary: "get a solution by id"
      operationId: getSolutionById
      parameters:
        - $ref: '#/components/parameters/SolutionId'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      tags:
        - modelmanager
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './shared-oas.yaml#/components/schemas/Solution'
        404:
          $ref: '#/components/responses/NotFound'
    put:
      summary: "update a solution by id"
      operationId: updateSolutionById
      parameters:
        - $ref: '#/components/parameters/SolutionId'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      tags:
        - modelmanager
      requestBody:
        content:
          application/json:
            schema:
              $ref: './shared-oas.yaml#/components/schemas/Solution'
      responses:
        200:
          description: "Solution updated"
          content:
            application/json:
              schema:
                $ref: './shared-oas.yaml#/components/schemas/Solution'
    delete:
      summary: "delete a solution by id"
      operationId: deleteSolutionById
      parameters:
        - $ref: '#/components/parameters/SolutionId'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      tags:
        - modelmanager
      responses:
        204:
          $ref: '#/components/responses/Deleted'

  "/apis/v1beta1/model-manager/solutions/{solutionId}/model":
    get:
      summary: "get put url for model of solution"
      operationId: getModelPutUrl
      tags:
        - modelmanager
      parameters:
        - $ref: '#/components/parameters/SolutionId'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      responses:
        200:
          $ref: '#/components/responses/PutUrlResponse'

  "/apis/v1beta1/model-manager/solutions/{solutionId}/prediction-template":
    get:
      summary: "get put url for prediction template of solution"
      operationId: getPredictionTemplatePutUrl
      tags:
        - modelmanager
      parameters:
        - $ref: '#/components/parameters/SolutionId'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      responses:
        200:
          $ref: '#/components/responses/PutUrlResponse'

  "/apis/v1beta1/model-manager/predictions":
    get:
      summary: "get predictions"
      operationId: getPredictions
      tags:
        - modelmanager
      parameters:
        - $ref: './shared-oas.yaml#/components/parameters/User'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './shared-oas.yaml#/components/schemas/Prediction'
    post:
      summary: "create prediction"
      operationId: createPrediction
      tags:
        - modelmanager
      parameters:
        - $ref: './shared-oas.yaml#/components/parameters/User'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './shared-oas.yaml#/components/schemas/Prediction'
      responses:
        201:
          description: "Resource created"
          content:
            application/json:
              schema:
                $ref: './shared-oas.yaml#/components/schemas/Prediction'

  "/apis/v1beta1/model-manager/predictions/{predictionId}":
    get:
      summary: "get prediction by id"
      operationId: getPredictionById
      tags:
        - modelmanager
      parameters:
        - $ref: '#/components/parameters/PredictionId'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './shared-oas.yaml#/components/schemas/PredictionId'
        404:
          $ref: '#/components/responses/NotFound'
    put:
      summary: "update prediction"
      operationId: updatePredictionById
      tags:
        - modelmanager
      parameters:
        - $ref: '#/components/parameters/PredictionId'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './shared-oas.yaml#/components/schemas/Prediction'
      responses:
        200:
          description: "Prediction updated"
          content:
            application/json:
              schema:
                $ref: './shared-oas.yaml#/components/schemas/Prediction'
    delete:
      summary: "delete Prediction"
      operationId: deletePredictionById
      tags:
        - modelmanager
      parameters:
        - $ref: '#/components/parameters/PredictionId'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      responses:
        204:
          $ref: '#/components/responses/Deleted'

components:
  schemas:
    Error:
      required:
        - path
        - error
        - timestamp
        - message
        - status
    User:
      $ref: './shared-oas.yaml#/components/schemas/User'
    OIDCUser:
      $ref: './shared-oas.yaml#/components/schemas/OIDCUser'
    DatabagType:
      $ref: './shared-oas.yaml#/components/schemas/DatabagType'
    PutUrl:
      type: string
    DatasetPutUrl:
      properties:
        url:
          $ref: '#/components/schemas/PutUrl'
        databagId:
          $ref: './shared-oas.yaml#/components/schemas/DatabagId'
  parameters:
    DatabagId:
      name: databagId
      in: path
      description: Id of Databag
      required: true
      schema:
        $ref: './shared-oas.yaml#/components/schemas/DatabagId'
    SolutionId:
      name: solutionId
      in: path
      description: Id of the Solution
      required: true
      schema:
        $ref: './shared-oas.yaml#/components/schemas/SolutionId'
    PredictionId:
      name: predictionId
      in: path
      description: Id of the Prediction
      required: true
      schema:
        $ref: './shared-oas.yaml#/components/schemas/PredictionId'
    SolverName:
      name: solverName
      in: path
      description: name of the solver
      required: true
      schema:
        type: string
    FileName:
      name: fileName
      in: path
      description: name of a file
      required: true
      schema:
        type: string
  responses:
    Created:
      description: New resource created
    Deleted:
      description: The specified resource was deleted
    Updated:
      description: The specified resource was updated
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    PutUrlResponse:
      description: The requested put url
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PutUrl'
    RequestBodyMismatch:
      description: The provided request body has the wrong format
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    RequestBodyInvalid:
      description: The content of the request body is invalid
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
