openapi: 3.0.3
info:
  title: Job Manager
  description: Job Manager
  version: 1.0.0
servers:
  - url: 'http://jobmanager.os4ml.svc.cluster.local:8000'
paths:
  "/apis/v1beta1/jobmanager/pipelines":
    get:
      summary: 'Get all pipelines'
      operationId: getPipelines
      parameters:
        - $ref: './shared-oas.yaml#/components/parameters/User'
      tags:
        - jobmanager
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pipeline'
    post:
      summary: 'Create Pipeline'
      operationId: createPipeline
      parameters:
        - $ref: './shared-oas.yaml#/components/parameters/User'
      tags:
        - jobmanager
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePipeline'
      responses:
        201:
          description: "Resource created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PipelineId'
  "/apis/v1beta1/jobmanager/runs":
    get:
      summary: 'Get all pipeline runs'
      operationId: getRuns
      parameters:
        - $ref: './shared-oas.yaml#/components/parameters/User'
      tags:
        - jobmanager
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Run'
  "/apis/v1beta1/jobmanager/runs/{runId}":
    get:
      summary: 'Get single pipeline run'
      operationId: getRunById
      parameters:
        - $ref: '#/components/parameters/RunId'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      tags:
        - jobmanager
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Run'
    delete:
      summary: 'Delete a run'
      operationId: deleteRunById
      parameters:
        - $ref: '#/components/parameters/RunId'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      tags:
        - jobmanager
      responses:
        204:
          description: "Deleted"

  "/apis/v1beta1/jobmanager/pipelines/{pipelineId}/run":
    post:
      summary: 'Create Run'
      operationId: createRun
      parameters:
        - $ref: '#/components/parameters/ExperimentId'
        - $ref: '#/components/parameters/PipelineId'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      tags:
        - jobmanager
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRun'
      responses:
        201:
          description: "Resource created"
          content:
            application/json:
              schema:
                $ref: './shared-oas.yaml#/components/schemas/RunId'

  "/apis/v1beta1/jobmanager/templates/{pipelineTemplateName}":
    post:
      summary: "Convenience route to run a Pipeline Template directly"
      operationId: runTemplate
      parameters:
        - $ref: '#/components/parameters/PipelineTemplateName'
        - $ref: './shared-oas.yaml#/components/parameters/User'
      tags:
        - jobmanager
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RunParams'
      responses:
        201:
          description: "Resource created"
          content:
            application/json:
              schema:
                $ref: './shared-oas.yaml#/components/schemas/RunId'

components:
  schemas:
    OIDCUser:
      $ref: './shared-oas.yaml#/components/schemas/OIDCUser'
    User:
      $ref: './shared-oas.yaml#/components/schemas/User'
    ExperimentId:
      type: string
    PipelineId:
      type: string
    Experiment:
      description: Experiment Object
      type: object
      required:
        - name
      properties:
        id:
          $ref: '#/components/schemas/ExperimentId'
        name:
          type: string
        description:
          type: string
    Pipeline:
      description: Pipeline Object
      type: object
      required:
        - name
        - description
      properties:
        id:
          $ref: '#/components/schemas/PipelineId'
        name:
          type: string
        description:
          type: string
    CreatePipeline:
      description: Create Pipeline Object
      allOf:
        - $ref: '#/components/schemas/Pipeline'
        - type: object
          required:
            - config_url
          properties:
            configUrl:
              type: string
    Metrics:
      description: Run Metrics
      type: object
      properties:
        name:
          type: string
        value:
          type: number
        format:
          type: string
    Run:
      description: Run Object
      type: object
      required:
        - name
      properties:
        id:
          $ref: './shared-oas.yaml#/components/schemas/RunId'
        name:
          type: string
        description:
          type: string
        status:
          type: string
        error:
          type: string
        metrics:
          type: array
          items:
            $ref: '#/components/schemas/Metrics'
    CreateRun:
      description: Create Run Object
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        params:
          $ref: '#/components/schemas/RunParams'
    RunParams:
      description: Default Parameters to start Run
      type: object
      properties:
        bucket:
          type: string
        fileName:
          type: string
        databagId:
          type: string
          nullable: true
        solutionName:
          type: string
    Error:
      required:
        - path
        - error
        - timestamp
        - message
        - status

  parameters:
    ExperimentId:
      name: experimentId
      in: path
      description: Id of Experiment
      required: true
      schema:
        $ref: '#/components/schemas/ExperimentId'
    PipelineId:
      name: pipelineId
      in: path
      description: Id of Pipeline
      required: true
      schema:
        $ref: '#/components/schemas/PipelineId'
    RunId:
      name: runId
      in: path
      description: Id of Run
      required: true
      schema:
        $ref: './shared-oas.yaml#/components/schemas/RunId'
    PipelineTemplateName:
      name: pipelineTemplateName
      in: path
      description: Name of the PipelineTemplate
      required: true
      schema:
        type: string
    SolutionName:
      name: solutionName
      in: path
      description: Name of the Solution
      required: true
      schema:
        type: string
  responses:
    Created:
      description: New resource created
    Deleted:
      description: The specified resource was deleted
    Updated:
      description: The specified resource was updated
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    RequestBodyMismatch:
      description: The provided request body has the wrong format
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    RequestBodyInvalid:
      description: The content of the request body is invalid
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
