include:
  - local: 'gitlab/shared/.gitlab-ci.prepare-validate-oas.yml'
  - local: 'gitlab/shared/.gitlab-ci.build-test.yml'
  - local: 'gitlab/shared/.gitlab-ci.build-images.yml'

# Build Jobmanager image
job-manager-validate-oas:
  extends:
    - .validate-oas
  variables:
    OAS_FILE: 'services/job-manager/oas/job-manager-oas.yaml'

job-manager-validate-backend:
  extends:
    - .build-development
  variables:
    DOCKERFILE: 'services/job-manager/Dockerfile'
    IMG_NAME: 'job-manager'
    BUILD_CONTEXT: '.'

job-manager-build:
  extends:
    - .build-production
  needs:
    - job-manager-validate-backend
  variables:
    DOCKERFILE: 'services/job-manager/Dockerfile'
    IMG_NAME: 'job-manager'
    BUILD_CONTEXT: '.'
