include:
  - local: 'gitlab/shared/.gitlab-ci.prepare-validate-oas.yml'
  - local: 'gitlab/shared/.gitlab-ci.build-development.yml'
  - local: 'gitlab/shared/.gitlab-ci.build-production.yml'

# Build Jobmanager image
job-manager-validate-oas:
  extends:
    - .validate-oas
  variables:
    OAS_FILE: 'services/job-manager/oas/job-manager-oas.yaml'

job-manager-validate-backend:
  extends:
    - .build-development
  variables:
    DIR: 'services/job-manager'
    IMG_NAME: 'job-manager'

job-manager-build:
  extends:
    - .build-production
  needs:
    - job-manager-validate-backend
  variables:
    DIR: 'services/job-manager'
    IMG_NAME: 'job-manager'
