include:
  - local: 'gitlab/shared/.gitlab-ci.validate-oas.yml'
  - local: 'gitlab/shared/.gitlab-ci.build-test-and-lint.yml'
  - local: 'gitlab/shared/.gitlab-ci.build-production.yml'

model-manager-validate-oas:
  extends:
    - .validate-oas
  variables:
    OAS_FILE: 'services/model-manager/oas/model-manager-oas.yaml'

model-manager-test-and-lint:
  extends:
    - .build-test-and-lint
  variables:
    DOCKERFILE: 'services/model-manager/Dockerfile'
    IMG_NAME: 'os4ml-model-manager'
    BUILD_CONTEXT: 'services/model-manager'

model-manager-build:
  extends:
    - .build-production
  needs:
    - os-manager-test-and-lint
  variables:
    DOCKERFILE: 'services/model-manager/Dockerfile'
    IMG_NAME: 'os4ml-model-manager'
    BUILD_CONTEXT: 'services/model-manager'
    IMAGE_REGISTRY: 'wogra'
