include:
  - local: 'gitlab/shared/.gitlab-ci.build-production.yml'

.build-frontend:
  stage: build
  needs: [ ]
  image: $CI_REGISTRY/developer/images/node-java:node-18-jre-16
  script:
    - cd $DIR
    - npm ci --cache .npm_cache
    - npm run lint
    - npm run build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE

build-frontend:
  extends:
    - .build-frontend
  variables:
    DIR: 'services/frontend'
    IMG_NAME: 'frontend'
  artifacts:
    paths:
      - services/frontend/dist/os4ml
  cache:
    key: frontend
    paths:
      - services/frontend/node_modules
      - services/frontend/.npm_cache

build-frontend-image:
  extends:
    - .build-production
  needs:
    - build-frontend
  dependencies:
    - build-frontend
  variables:
    DOCKERFILE: 'services/frontend/Dockerfile'
    IMG_NAME: 'os4ml-frontend'
    BUILD_CONTEXT: 'services/frontend'
    IMAGE_REGISTRY: 'wogra'