include:
  - local: 'gitlab/shared/.gitlab-ci.validate-oas.yml'
  - local: 'gitlab/shared/.gitlab-ci.build-test-and-lint.yml'
  - local: 'gitlab/shared/.gitlab-ci.build-production.yml'

workflow-translator-validate-oas:
  extends:
    - .validate-oas
  variables:
    OAS_FILE: 'services/workflow-translator/oas/workflow-translator-oas.yaml'

workflow-translator-test-and-lint:
  extends:
    - .build-test-and-lint
  variables:
    DOCKERFILE: 'services/workflow-translator/Dockerfile'
    IMG_NAME: 'workflow-translator'
    BUILD_CONTEXT: '.'

workflow-translator-build:
  extends:
    - .build-production
  needs:
    - workflow-translator-test-and-lint
  variables:
    DOCKERFILE: 'services/workflow-translator/Dockerfile'
    IMG_NAME: 'workflow-translator'
    BUILD_CONTEXT: '.'
