include:
  - local: 'gitlab/shared/.gitlab-ci.validate-oas.yml'
  - local: 'gitlab/shared/.gitlab-ci.build-test-and-lint.yml'
  - local: 'gitlab/shared/.gitlab-ci.build-production.yml'

job-manager-validate-oas:
  extends:
    - .validate-oas
  variables:
    OAS_FILE: 'services/job-manager/oas/job-manager-oas.yaml'

job-manager-test-and-lint:
  extends:
    - .build-test-and-lint
  variables:
    DOCKERFILE: 'services/job-manager/Dockerfile'
    IMG_NAME: 'job-manager'
    BUILD_CONTEXT: '.'

job-manager-build:
  extends:
    - .build-production
  needs:
    - job-manager-test-and-lint
  variables:
    DOCKERFILE: 'services/job-manager/Dockerfile'
    IMG_NAME: 'job-manager'
    BUILD_CONTEXT: '.'
