include:
  - local: 'gitlab/shared/.gitlab-ci.prepare-validate-oas.yml'
  - local: 'gitlab/shared/.gitlab-ci.build-test.yml'
  - local: 'gitlab/shared/.gitlab-ci.build-images.yml'

os-manager-validate-oas:
  extends:
    - .validate-oas
  variables:
    OAS_FILE: 'services/objectstore-manager/oas/objectstore-manager-oas.yaml'

os-manager-validate-backend:
  extends:
    - .build-development
  variables:
    DOCKERFILE: 'services/objectstore-manager/Dockerfile'
    IMG_NAME: 'objectstore-manager'
    BUILD_CONTEXT: 'services/objectstore-manager'

os-manager-build:
  extends:
    - .build-production
  needs:
    - os-manager-validate-backend
  variables:
    DOCKERFILE: 'services/objectstore-manager/Dockerfile'
    IMG_NAME: 'objectstore-manager'
    BUILD_CONTEXT: 'services/objectstore-manager'
