include:
  - local: 'gitlab/shared/.gitlab-ci.validate-oas.yml'
  - local: 'gitlab/shared/.gitlab-ci.build-test-and-lint.yml'
  - local: 'gitlab/shared/.gitlab-ci.build-production.yml'

os-manager-validate-oas:
  extends:
    - .validate-oas
  variables:
    OAS_FILE: 'services/objectstore-manager/oas/objectstore-manager-oas.yaml'

os-manager-test:
  extends:
    - .build-test
  variables:
    DOCKERFILE: 'services/objectstore-manager/Dockerfile'
    IMG_NAME: 'objectstore-manager'
    BUILD_CONTEXT: 'services/objectstore-manager'

os-manager-lint:
  extends:
    - .build-lint
  variables:
    DOCKERFILE: 'services/objectstore-manager/Dockerfile'
    IMG_NAME: 'objectstore-manager'
    BUILD_CONTEXT: 'services/objectstore-manager'

os-manager-build:
  extends:
    - .build-production
  needs:
    - os-manager-test
    - os-manager-lint
  variables:
    DOCKERFILE: 'services/objectstore-manager/Dockerfile'
    IMG_NAME: 'objectstore-manager'
    BUILD_CONTEXT: 'services/objectstore-manager'
