import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from api.controller.objectstore_api_controller import ObjectstoreApiController
from build.openapi_server.models.user import User
from repository.impl.minio_repository import MinioRepository
from services.databag_service import DatabagService
from services.storage_service import StorageService
from src.main import app as application

user_header = {
    "usertoken": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJpUWR1ZW1PVlpfUVNCTDg5YTVjWFZiYjgzbEY2dGR3LVZLMjlCTnZUaHl3In0.eyJleHAiOjE2NjU3NTQ0MDIsImlhdCI6MTY2NTc1NDEwMiwiYXV0aF90aW1lIjoxNjY1NzU0MTAyLCJqdGkiOiI0NjgzMGY1YS0xOThmLTRlNjYtOTljMy01YTJkNzE0OGJjNjAiLCJpc3MiOiJodHRwczovL2xvZ2luLm9zNG1sLndvZ3JhLmNvbS9yZWFsbXMvb3M0bWwiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiNWQ0MTE3MGYtMWI3MS00YjZlLThiMjYtNjMxZjFhMzEwNDNlIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoia3ViZWZsb3ctb2lkYy1hdXRoc2VydmljZSIsIm5vbmNlIjoiSER4VTJTZVpVek1pdTJ1cUVRa3dOb0lMWXhxMXRYSjZSTGRtdE04bmxSdyIsInNlc3Npb25fc3RhdGUiOiIwY2YyZTI2Yy00Yjk0LTQwMjAtYWQwZS04M2JiMDNhMzIzOTgiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLW9zNG1sIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInNpZCI6IjBjZjJlMjZjLTRiOTQtNDAyMC1hZDBlLTgzYmIwM2EzMjM5OCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiZXhhbXBsZSB1c2VyIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidXNlckBleGFtcGxlLmNvbSIsImdpdmVuX25hbWUiOiJleGFtcGxlIiwiZmFtaWx5X25hbWUiOiJ1c2VyIiwiZW1haWwiOiJ1c2VyQGV4YW1wbGUuY29tIn0.G7VS76tQ_RpOdmn311rou-ERGoHVzjO0HBmd4ug0m6qukTWra4_LgCqvHrrdwTP4sOnZA5qkwXhA44xQ0g7wNptsg8SIEA6_QZTCCJmyji34_8eeRbk1EiUzOtvtue3Hp2vldXjMXixgwUGTh7G82qPRXUyinBVTIZgA8zgrNlECv15X_exxDu55j-58IBld_ZMW7HzNuwxPlZ3as9vKLJaEoM5UqTLV13d_nPlFu7b1K1j8tHqF5AVMMRMul3MFmlz2m21HGdzRzkgwqJktObjwE7Ztqt-l4PBQpQSQp3G6zRuLeHib3kpSQ_76Zqb5dh4KvChBJzZrLDXcgkSHSQ"
}


@pytest.fixture
def app() -> FastAPI:
    application.dependency_overrides = {}

    return application


@pytest.fixture
def client(app) -> TestClient:
    return TestClient(app)


@pytest.fixture
def minio_mock(mocker):
    return mocker.Mock()


@pytest.fixture
def api_service_mock(minio_mock):
    mock_minio_repository = MinioRepository(client=minio_mock)
    mock_storage_service = StorageService(mock_minio_repository)
    mock_databag_service = DatabagService(mock_minio_repository)
    return ObjectstoreApiController(
        storage_service=mock_storage_service,
        databag_service=mock_databag_service,
        user=User(id="default", email="email", raw_token=""),
    )
