apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobmanager
  namespace: os4ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: os4ml
      name: jobmanager
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: os4ml
        name: jobmanager
    spec:
      containers:
        - name: jobmanager
          image: "gitlab-registry.wogra.com/developer/wogra/os4ml/job-manager"
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: ML_PIPELINE_URL
              valueFrom:
                configMapKeyRef:
                  name: jobmanager-config
                  key: pipelineUrl
            - name: ML_PIPELINE_NS
              valueFrom:
                configMapKeyRef:
                  name: jobmanager-config
                  key: pipelineNS
            - name: KF_PIPELINES_SA_TOKEN_PATH
              value: /var/run/secrets/kubeflow/pipelines/token
          volumeMounts:
            - mountPath: /var/run/secrets/kubeflow/pipelines
              name: volume-kf-pipeline-token
              readOnly: true
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
      serviceAccountName: default-editor
      imagePullSecrets:
        - name: registry-credentials
      volumes:
        - name: volume-kf-pipeline-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 7200
                  audience: pipelines.kubeflow.org