apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobmanager
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: os4ml
      app.kubernetes.io/component: jobmanager
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: os4ml
        app.kubernetes.io/component: jobmanager
    spec:
      containers:
        - name: jobmanager
          image: "wogra/os4ml-job-manager"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          env:
            - name: ML_PIPELINE_URL
              valueFrom:
                configMapKeyRef:
                  name: jobmanager-config
                  key: pipelineUrl
            - name: ML_PIPELINE_NS
              valueFrom:
                configMapKeyRef:
                  name: jobmanager-config
                  key: pipelineNS
            - name: OS4ML_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: jobmanager-config
                  key: os4mlNS
            - name: KF_PIPELINES_SA_TOKEN_PATH
              value: /var/run/secrets/kubeflow/pipelines/token
            - name: OS4ML_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: jobmanager-config
                  key: os4mlBucket
          volumeMounts:
            - mountPath: /var/run/secrets/kubeflow/pipelines
              name: volume-kf-pipeline-token
              readOnly: true
          resources:
            limits:
              cpu: 500m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          startupProbe:
            httpGet:
              port: http
              path: /docs
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: http
              path: /docs
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 4
          livenessProbe:
            httpGet:
              port: http
              path: /docs
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 4
          securityContext:
            allowPrivilegeEscalation: false
      serviceAccountName: service-account
      imagePullSecrets:
        - name: registry-credentials
      volumes:
        - name: volume-kf-pipeline-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 7200
                  audience: pipelines.kubeflow.org
