apiVersion: v1
kind: Service
metadata:
  name: jobmanager
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
      targetPort: http
      name: api
  selector:
    app.kubernetes.io/name: os4ml
    app.kubernetes.io/component: jobmanager